        <div class="row-fluid">
          <div class="hero-unit">
            <h2>Gestion des messages de fundation</h2>
          </div>
        </div>
        <div class="row-fluid">
            <?php if(isset($this->param['alert'])) {
                $alert = $this->param['alert']; ?>
                <div class="<?php echo $alert['class']; ?>">
                    <strong><?php echo $alert['strong']; ?></strong> <?php echo $alert['message']; ?>
                </div>
            <?php } ?>
        </div>
        <div class="row-fluid">
            <p><strong>Message actuel de la fundation :</strong> <?php echo $this->param['current_msg']; ?></p>
            <form method="POST" action="<?php echo $this->param['set_url']; ?>" >
                <p>Nouveau message :</p>
                <input type="text" name="message"/>
                <button type="submit">Changer</button>
                <input type="hidden" name="module" value="messages"/>
                <input type="hidden" name="fun_id" value="<?php echo $this->param['fun_id']; ?>"/>

          </form>

        </div>
