<?php
$user_data = $_SESSION['json_client_status']->user_data;
$username = ucfirst($user_data->firstname)." ".ucfirst($user_data->lastname);
?>
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title><?php echo $this->title ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Le styles -->
    <?php $this->echo_cssfiles(); ?>
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->index_link; ?>"><?php echo $this->title; ?></a>
          <div class="btn-group pull-right">
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="icon-user"></i> <?php echo $username ?>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="../">Mon compte</a></li>
              <li class="divider"></li>
              <li><a href="?logout">Déconnexion</a></li>
            </ul>
          </div>
          <div class="nav-collapse">
            <ul class="nav">
              <?php
              foreach($this->menus as $menu) {
                $li_class=$menu['class'];
                $a_class='';
                $a_more='';
                if(isset($menu['submenu'])) {
                  $li_class.=' dropdown';
                  $a_more.='data-toggle="dropdown"';
                }
                echo '<li class="'.$li_class.'" >';
                echo '<a href="'.$menu['link'].'" class="" '.$a_more.'>';
                echo $menu['content'];
                if(isset($menu['submenu'])) {
                  echo '<b class="caret"></b>';
                }
                echo '</a>';
                if(isset($menu['submenu'])) {
                  echo '<ul class="dropdown-menu">';
                    $submenus = $menu['submenu'];
                    foreach($submenus as $submenu) {
                        echo '<li class="'.$submenu['class'].'" >';
                        echo '<a href="'.$submenu['link'].'" class="" >';
                        echo $submenu['content'];
                        echo '</a>';
                        echo '</li>';
                    }
                  echo '</ul>';
                }
                echo '</li>';
              }
              ?>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <div class="container-fluid">
  	 <?php echo $this->get_container() ?>
    <hr>

      <footer>
        <p>&copy; <?php echo $this->copyright ?></p>
      </footer>
</div><!--/.fluid-container-->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <?php $this->echo_jsfiles(); ?>

  </body>
</html>
