	  <script>
  			var summary = <?php echo json_encode($this->param['summary']); ?>;
        summary = summary["success"] || [];

	  </script>
    <div class="hero-unit">
      <h1>Trésorerie</h1>
    </div>
    <div id="treso">
      <p>Choisissez une ou deux dates pour en avoir le resumé d'un jour ou d'une période:  
        <form action="" method="GET" id="dates">
          Du <input type="text" id="datepicker"/> au 
          <input type="text" id="datepicker2"/>
          <input type="submit" />
        </form>
      </p>
      <? if (isset($this->param["day"])) {
          echo "<a href='?";
          foreach ($_GET as $key => $value) {
            if ($key != "action")
              echo  $key . "=" . $value . "&";
          }
          echo "action=download";
          echo "''>Télécharger le rapport</a>";
            if (!isset($this->param["day2"]))  
                echo "<h2>Statistiques pour le " . $this->param["day"] . "/" . $this->param["month"] . "/" . $this->param["year"] . "</h2>";
            else {
                echo "<h2>Statistiques du " . $this->param["day"] . "/" . $this->param["month"] . "/" . $this->param["year"];
                echo " au " . $this->param["day2"] . "/" . $this->param["month2"] . "/" . $this->param["year2"] . "</h2>";
            }
        }
        else {
          echo "Veuillez choisir une date.";
        }  ?>
    </div>