<?php

function formatPrix($p) {
  return number_format($p, 2, ',', ' ') . " €";
}

$fundation = array();


?>
<style>
.text-right {
  text-align: right;
}
</style>

<div class="container">

<div class="row">
  <div class="span12">
    <h1>Gestion trésorerie de payutc</h1>
    <br />
  </div>
  <div class="span6 well">
    <h2>Statistiques</h2>

    <table class="table">
      <tr>
        <td><strong>Ventes depuis toujours : </strong></td>
        <td><p class="text-right"><?php echo formatPrix($this->param['details']->amount_total / 100); ?></p></td>
      </tr>
      <tr>
        <td><strong>Somme des comptes : </strong></td>
        <td><p class="text-right"><?php echo formatPrix($this->param['details']->account_total / 100); ?></p></td>
      </tr>
      <tr>
        <td><strong>Somme non reversés : </strong></td>
        <td><p class="text-right"><?php echo formatPrix(($this->param['details']->amount_total - $this->param['details']->reversement_total) / 100); ?></p></td>
      </tr>
      <tr>
        <td><strong>En attente de reversement : </strong></td>
        <td><p class="text-right"><?php echo formatPrix($this->param['details']->reversement_wait / 100); ?></p></td>
      </tr>
      <tr>
        <td><strong>Montant minimum à avoir sur le compte : </strong></td>
        <td><p class="text-right"><?php echo formatPrix(($this->param['details']->amount_total - $this->param['details']->reversement_total + $this->param['details']->account_total) / 100); ?></p></td>
      </tr>
    </table>
  </div>
  <div class="span11 well">
    <h2>Fundations</h2>
    <table class="table">
      <thead>
        <th>Fundation</th>
        <th><p class="text-right">Montant total</p></th>
        <th><p class="text-right">Solde</p></th>
        <th><p class="text-right">Dernier reversement</p></th>
        <th><p class="text-right">En attente de reversement</p></th>
        <th></th>
      </thead>
      <tbody>
        <?php foreach($this->param['details']->fundations as $fun) { 
          $fundation[$fun->id] = $fun->name; ?>
        <tr>
          <td><?php echo $fun->name; ?></td>
          <td><p class="text-right"><?php echo formatPrix($fun->amount_total / 100); ?></p></td>
          <td><p class="text-right"><?php echo formatPrix(($fun->amount_total - $fun->reversement_total)/100); ?></p></td>
          <td><p class="text-right"><?php if($fun->reversement_last) {
            $rev = $fun->reversement_last;
            echo formatPrix($rev->amount/100) ." le ".$rev->updated;
          } else {
            echo "aucun";
          }?></p></td>
          <td><p class="text-right"><?php if($fun->reversement_wait) {
            $rev = $fun->reversement_wait;
            echo formatPrix($rev->amount/100) ." demandé le ".$rev->created;
          } else {
            echo "aucun";
          }?></p></td>
          <td><?php
            if($fun->reversement_wait != null) {
              echo '<a href="'.$this->param['url_rev'].'&rev_id='.$fun->reversement_wait->id.'" class="btn btn-primary">Reverser</a>';
            }
          ?></td>
        </tr>
        <?php } ?>
      </tbody>
    </table>
  </div>
  <div class="span11 well">
    <h2>Reversements</h2>
    <table class="table">
      <thead>
        <th>Fundation</th>
        <th>Demande</th>
        <th>Realisation</th>
        <th><p class="text-right">Montant</p></th>
        <th><p class="text-right">Frais</p></th>
        <th><p class="text-right">Montant reversé</p></th>
      </thead>
      <tbody>
        <?php foreach($this->param['details']->reversements as $rev) { ?>
        <tr>
          <td><?php echo $fundation[$rev->funId]; ?></td>
          <td><?php echo $rev->created; ?></p></td>
          <td><?php echo $rev->updated; ?></p></td>
          <td><p class="text-right"><?php echo formatPrix(($rev->amount)/100); ?></p></td>
          <td><p class="text-right"><?php echo formatPrix(($rev->frais)/100); ?> ( <?php echo number_format($rev->taux / 100, 2, ',', ' '); ?> %)</p></td>
          <td><p class="text-right"><?php echo formatPrix(($rev->amount - $rev->frais)/100); ?></p></td>
        </tr>
        <?php } ?>
      </tbody>
    </table>
  </div>
</div>

</div>