<div class="container">

<div class="row">
  <div class="span12">
    <h1>Gestion trésorerie assos <?php echo $this->param['fundation']->name; ?></h1>
    <br />
  </div>
  <div class="span5 well">
    <h2>Statistiques</h2>

    <table class="table">
      <tr><td><strong>Ventes depuis toujours : </strong></td><td><?php echo $this->param['details']->amount_total / 100; ?> € </td></tr>
      <tr><td><strong>Somme non reversés : </strong></td><td><?php echo ($this->param['details']->amount_total - $this->param['details']->reversement_total) / 100; ?> € </td></tr>
      <tr><td><strong>En attente de reversement : </strong></td><td><?php 
        if($this->param['details']->reversement_wait) {
            $rev = $this->param['details']->reversement_wait;
            echo $rev->amount/100 ." € demandé le ".$rev->created;
          } else {
            echo "aucun";
          } ?></td></tr>
      <tr><td><strong>Dernier reversement : </strong></td><td><?php 
        if($this->param['details']->reversement_last) {
            $rev = $this->param['details']->reversement_last;
            echo $rev->amount/100 ." € le ".$rev->updated;
          } else {
            echo "aucun";
          } ?></td></tr>
    </table>
    <?php
      if(($this->param['details']->amount_total - $this->param['details']->reversement_total) > 0 && $this->param['details']->reversement_wait == null) {
        echo '<a href="'.$this->param['url_ask'].'" class="btn btn-primary pull-right">Demander un reversement</a>';
      }
    ?>
  </div>
</div>

</div>