<?php

function formatPrix($p) {
  return number_format($p, 2, ',', ' ') . " €";
}

?>
<style>
.text-right {
  text-align: right;
}
</style>
<div class="container">

<div class="row">
  <div class="span12">
    <h1>Gestion trésorerie assos <?php echo $this->param['fundation']->name; ?></h1>
    <br />
  </div>
  <div class="span6 well">
    <h2>Statistiques</h2>

    <table class="table">
      <tr>
        <td><strong>Ventes depuis toujours : </strong></td>
        <td><p class="text-right"><?php echo formatPrix($this->param['details']->amount_total / 100); ?></td>
      </tr>
      <tr>
        <td><strong>Somme non reversés : </strong></td>
        <td><p class="text-right"><?php echo formatPrix($this->param['details']->amount_total - $this->param['details']->reversement_total / 100); ?></td>
      </tr>
      <tr>
        <td><strong>En attente de reversement : </strong></td>
        <td><p class="text-right"><?php 
        if($this->param['details']->reversement_wait) {
            $rev = $this->param['details']->reversement_wait;
            echo formatPrix($rev->amount/100) ." demandé le ".$rev->created;
          } else {
            echo "aucun";
          } ?></p></td>
      </tr>
      <tr>
        <td><strong>Dernier reversement : </strong></td>
        <td><p class="text-right"><?php 
        if($this->param['details']->reversement_last) {
            $rev = $this->param['details']->reversement_last;
            echo formatPrix($rev->amount/100) ." le ".$rev->updated;
          } else {
            echo "aucun";
          } ?></p></td>
      </tr>
    </table>
    <?php
      if(($this->param['details']->amount_total - $this->param['details']->reversement_total) > 0 && $this->param['details']->reversement_wait == null) {
        echo '<a href="'.$this->param['url_ask'].'" class="btn btn-primary pull-right">Demander un reversement</a>';
      }
    ?>
  </div>
  <div class="span11 well">
    <h2>Reversements</h2>
    <table class="table">
      <thead>
        <th>Demande</th>
        <th>Realisation</th>
        <th><p class="text-right">Montant</p></th>
        <th><p class="text-right">Frais</p></th>
        <th><p class="text-right">Montant reversé</p></th>
      </thead>
      <tbody>
        <?php foreach($this->param['details']->reversements as $rev) { ?>
        <tr>
          <td><?php echo $rev->created; ?></p></td>
          <td><?php echo $rev->updated; ?></p></td>
          <td><p class="text-right"><?php echo formatPrix(($rev->amount)/100); ?></p></td>
          <td><p class="text-right"><?php echo formatPrix(($rev->frais)/100); ?> ( <?php echo number_format($rev->taux / 100, 2, ',', ' '); ?> %)</p></td>
          <td><p class="text-right"><?php echo formatPrix(($rev->amount - $rev->frais)/100); ?></p></td>
        </tr>
        <?php } ?>
      </tbody>
    </table>
  </div>
</div>

</div>