      <div class="row-fluid">
          <div class="hero-unit">
            <h1>Gestion des plages horaires</h1>
          </div>
      </div><!--/row-->
            <?php foreach($this->param['tab'] as $fundation) { ?>
            <div class="row-fluid">
                <h1><?php echo $fundation["name"]; ?></h1>
                <?php if(isset($this->param['alert'][$fundation["id"]])) { 
                    $alert = $this->param['alert'][$fundation["id"]]; ?>
                  <div class="<?php echo $alert['class']; ?>">
                    <button class="close" data-dismiss="alert">×</button>
                    <strong><?php echo $alert['strong']; ?></strong> <?php echo $alert['message']; ?>
                  </div>
                <?php } ?>
                <form class="well form-inline" method="POST" action="<?php echo $fundation["url_add"]; ?>" >
                  <input type="text" class="input-small" name="debut" placeholder="Debut hh:mm">
                  <input type="text" class="input-small" name="fin" placeholder="Fin hh:mm">
                  <input type="text" class="input-large" name="nom" placeholder="Nom de la plage horaire">
                  <select class="input-large" name="poi">
                    <?php foreach($fundation["pois"] as $poi) { ?>
                      <option value="<?php echo $poi["id"]; ?>"><?php echo $poi["name"]; ?></option>
                    <?php } ?>
                  </select>
                  <button type="submit" class="btn btn-success">Ajouter la plage horaire</button>
                </form>
                <table class="table table-striped table-bordered">
                    <thead>
                      <tr><th>Début</th><th>Fin</th><th>Nom</th><th>Point de vente</th><th></th></tr>
                    </thead>
                    <tbody>
                    <?php $plages = $fundation["plages"]; 
                      foreach($plages as $plage) { ?>
                      <tr><td><?php echo sprintf('%02d', substr($plage['start'],0,2)).":".sprintf('%02d', substr($plage['start'],2,2)); ?></td>
                          <td><?php echo sprintf('%02d', substr($plage['end'],0,2)).":".sprintf('%02d', substr($plage['end'],2,2)); ?></td>
                          <td><?php echo $plage['name']; ?></td>
                          <td><?php echo $plage['poi_name']; ?></td>
                          <td><a class="btn btn-danger" href="<?php echo $fundation["url_remove"]."&fun_id=".$fundation["id"]."&pla_id=".$plage['id']; ?>">Supprimer la plage horaire</a></td>
                      </tr>
                    <?php } ?>
                    </tbody>
                </table>
             <?php  } ?>
             <br />
          </div>
