      <div class="row-fluid">
          <div class="hero-unit">
            <h1>Gestion des droits</h1>
          </div>
      </div><!--/row-->
            <?php foreach($this->param['tab'] as $fundation) { ?>
            <div class="row-fluid">
                <h1><?php echo $fundation["name"]; ?></h1>
                <?php if(isset($this->param['alert'][$fundation["id"]])) { 
                    $alert = $this->param['alert'][$fundation["id"]]; ?>
                  <div class="<?php echo $alert['class']; ?>">
                    <button class="close" data-dismiss="alert">×</button>
                    <strong><?php echo $alert['strong']; ?></strong> <?php echo $alert['message']; ?>
                  </div>
                <?php } ?>
                <form class="well form-inline" method="POST" action="<?php echo $fundation["url_add"]; ?>" >
                  <input type="text" class="input-small" name="login"placeholder="Login utc">
                  <select class="input-small" name="right">
                    <option value="ADMIN">ADMIN</option>
                    <option value="GESARTICLE">GESARTICLE</option>
                    <option value="VENDRE">VENDRE</option>
                    <option value="TRESO">TRESO</option>
                  </select>
                  <button type="submit" class="btn btn-success">Ajouter le droit</button>
                </form>
                <table class="table table-striped table-bordered">
                    <thead>
                      <tr><th>Login</th><th>Nom</th><th>Prénom</th><th>Droit</th><th></th></tr>
                    </thead>
                    <tbody>
                    <?php $rights = $fundation["right"]; 
                      foreach($rights as $right) { ?>
                      <tr><td><?php echo $right['usr_login']; ?></td>
                          <td><?php echo $right['usr_lastname']; ?></td>
                          <td><?php echo $right['usr_firstname']; ?></td>
                          <td><?php echo $right['rig_id']; ?></td>
                          <td><a class="btn btn-danger" href="<?php echo $fundation["url_remove"]."&rig_id=".$right['rig_id']."&usr_id=".$right['usr_id']."&fun_id=".$fundation["id"]; ?>">Supprimer le droit</a></td>
                      </tr>
                    <?php } ?>
                    </tbody>
                </table>
             <?php  } ?>
             <br />
          </div>
