<div class="row-fluid">
	<div class="span3">
		<div class="well sidebar-nav" style="padding: 20px">
			<div id="tree"></div>
		</div><!--/.well -->
	</div><!--/span-->
	<div class="span9">
		<button id="tojson" class="btn">to json</button>
		<button id="refresh" class="btn">refresh</button>
		<div class="hero-unit">
			<div id="alert"></div>
			<div id="article_details" style="display: none;">
				<h2><span id="article_name"></span>(#<span id="article_id"></span>)</h2>
				<form class="form-horizontal">
					<fieldset>
						<div class="control-group">
							<label class="control-label" for="article_field_name">Nom</label>
							<div class="controls">
								<input name="name" class="input-xlarge focused" id="article_field_name" type="text">
							</div>
						</div>
						<div class="control-group">
							<label class="control-label" for="article_field_price">Prix</label>
							<div class="controls">
							<div class="input-append">
								<input name="price" id="article_field_price" class="input-xlarge" size="16" type="text"><span class="add-on">€</span>
							</div>
						</div>
						<div class="form-actions">
							<button id="save_article" type="submit" class="btn btn-primary">Save changes</button>
						</div>
					</fieldset>
				</form>
			</div>
			<div id="categorie_details" style="display: none;">
				<h2><span id="categorie_name"></span>(#<span id="categorie_id"></span>)</h2>
				<form class="form-horizontal">
					<fieldset>
						<div class="control-group">
							<label class="control-label" for="categorie_field_name">Nom</label>
							<div class="controls">
								<input name="name" class="input-xlarge focused" id="categorie_field_name" type="text">
							</div>
						</div>
						<div class="form-actions">
							<button id="save_categorie" type="submit" class="btn btn-primary">Save changes</button>
						</div>
					</fieldset>
				</form>
			</div>
		</div>
	</div><!--/span-->


</div><!--/row-->
