<div class="container-fluid">
	<div class="row-fluid">
		<div class="span3">
			<div class="well sidebar-nav">
				<div id="tree1"></div>
			</div><!--/.well -->
		</div><!--/span-->
		<div class="span9">
			<button id="tojson" class="btn">to json</button>
			<button id="refresh" class="btn">refresh</button>
			<div class="hero-unit">
				<div>
					<h2><span id="article_name"></span>(#<span id="article_id"></span>)</h2>
					<form class="form-horizontal">
						<fieldset>
							<div class="control-group">
								<label class="control-label" for="article_field_name">Nom</label>
								<div class="controls">
									<input name="price" class="input-xlarge focused" id="article_field_name" type="text">
								</div>
							</div>
							<div class="control-group">
								<label class="control-label" for="article_field_price">Prix</label>
								<div class="controls">
								<div class="input-append">
									<input name="price" id="article_field_price" class="span2" size="16" type="text">
									<span class="add-on">€</span>
								</div>
							</div>
							<div class="form-actions">
								<button type="submit" class="btn btn-primary">Save changes</button>
								<button class="btn">Cancel</button>
							</div>
						</fieldset>
					</form>
				</div>
			</div>
		</div><!--/span-->

		<div>
			<h2 id="categorie_name"></h2>
		</div>
		
		
		<form class="form-horizontal">
			<fieldset>
			  <div class="control-group">
				<label class="control-label" for="focusedInput">Focused input</label>
				<div class="controls">
				  <input class="input-xlarge focused" id="focusedInput" type="text" value="This is focused…">
				</div>
			  </div>
			  <div class="control-group">
				<label class="control-label">Uneditable input</label>
				<div class="controls">
				  <span class="input-xlarge uneditable-input">Some value here</span>
				</div>
			  </div>
			  <div class="input-append">
				<input name="price" id="price" class="span2" size="16" type="text">
				<span class="add-on">.00</span>
			  </div>
			  <div class="control-group warning">
				<label class="control-label" for="inputWarning">Input with warning</label>
				<div class="controls">
				  <input type="text" id="inputWarning">
				  <span class="help-inline">Something may have gone wrong</span>
				</div>
			  </div>
			  <div class="control-group error">
				<label class="control-label" for="inputError">Input with error</label>
				<div class="controls">
				  <input type="text" id="inputError">
				  <span class="help-inline">Please correct the error</span>
				</div>
			  </div>
			  <div class="control-group success">
				<label class="control-label" for="inputSuccess">Input with success</label>
				<div class="controls">
				  <input type="text" id="inputSuccess">
				  <span class="help-inline">Woohoo!</span>
				</div>
			  </div>
			  <div class="control-group success">
				<label class="control-label" for="selectError">Select with success</label>
				<div class="controls">
				  <select id="selectError">
					<option>1</option>
					<option>2</option>
					<option>3</option>
					<option>4</option>
					<option>5</option>
				  </select>
				  <span class="help-inline">Woohoo!</span>
				</div>
			  </div>
			  <div class="form-actions">
				<button type="submit" class="btn btn-primary">Save changes</button>
				<button class="btn">Cancel</button>
			  </div>
			</fieldset>
		</form>
  
	</div><!--/row-->

</div>
