<div class="container-fluid">
	<div class="row-fluid">
		<div class="span3">
			<div class="well sidebar-nav">
				<div id="tree1"></div>
			</div><!--/.well -->
		</div><!--/span-->
		<div class="span9">
			<div class="hero-unit">
				<h1>Hello, world!</h1>
				<p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
				<p><a class="btn btn-primary btn-large">Learn more »</a></p>
			</div>
			<button id="tojson" class="btn">to json</button>
			<button id="refresh" class="btn">refresh</button>
		</div><!--/span-->

		<div>
			<h2>Nom de la catégorie</h2>
		</div>
		
		<form class="form-horizontal">
			<fieldset>
			  <div class="control-group">
				<label class="control-label" for="focusedInput">Focused input</label>
				<div class="controls">
				  <input class="input-xlarge focused" id="focusedInput" type="text" value="This is focused…">
				</div>
			  </div>
			  <div class="control-group">
				<label class="control-label">Uneditable input</label>
				<div class="controls">
				  <span class="input-xlarge uneditable-input">Some value here</span>
				</div>
			  </div>
			  <div class="input-append">
				<input name="price" id="price" class="span2" size="16" type="text">
				<span class="add-on">.00</span>
			  </div>
			  <div class="control-group warning">
				<label class="control-label" for="inputWarning">Input with warning</label>
				<div class="controls">
				  <input type="text" id="inputWarning">
				  <span class="help-inline">Something may have gone wrong</span>
				</div>
			  </div>
			  <div class="control-group error">
				<label class="control-label" for="inputError">Input with error</label>
				<div class="controls">
				  <input type="text" id="inputError">
				  <span class="help-inline">Please correct the error</span>
				</div>
			  </div>
			  <div class="control-group success">
				<label class="control-label" for="inputSuccess">Input with success</label>
				<div class="controls">
				  <input type="text" id="inputSuccess">
				  <span class="help-inline">Woohoo!</span>
				</div>
			  </div>
			  <div class="control-group success">
				<label class="control-label" for="selectError">Select with success</label>
				<div class="controls">
				  <select id="selectError">
					<option>1</option>
					<option>2</option>
					<option>3</option>
					<option>4</option>
					<option>5</option>
				  </select>
				  <span class="help-inline">Woohoo!</span>
				</div>
			  </div>
			  <div class="form-actions">
				<button type="submit" class="btn btn-primary">Save changes</button>
				<button class="btn">Cancel</button>
			  </div>
			</fieldset>
		</form>
  
	</div><!--/row-->

</div>
