<div class="row-fluid">
	<div class="span5">
		<div id="treediv" class="well sidebar-nav" style="min-height: 200px;">
			<div id="tree"></div>
		</div><!--/.well -->
	</div><!--/span-->
	<div class="span7">
		<!--button id="tojson" class="btn">to json</button>
		<button id="refresh" class="btn">refresh</button-->
		<div id="detailsdiv">
			
			<div id="alert"></div>
			
			<div class="btn-group pull-right">
				<button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
					<i class="icon-plus icon-white"></i><span class="caret"></span>
				</button>
				<ul class="dropdown-menu">
					<li><a id="add_article">Article</a></li>
					<li><a id="add_categorie">Catégorie</a></li>
				</ul>
			</div>

			<!--div id="detailsdiv" class="pull-right"></div-->
			<!--			ARTICLE			-->
			<div id="article_details" style="display: none;">
				<h2><span id="article_name"></span> (#<span id="article_id"></span>)</h2>
				<form class="form-horizontal">
					<fieldset>
						<div class="control-group">
							<label class="control-label" for="article_field_categorie_id">Catégorie</label>
							<div class="controls">
								<select name="categorie_id" id="article_field_categorie_id" class="input-xlarge">
									<?php foreach($this->param['categories'] as $categorie)
										echo '<option value="'.$categorie['id'].'">'.$categorie['name'].'</option>';
									?>
								</select>
							</div>
						</div>
						<div class="control-group">
							<label class="control-label" for="article_field_name">Nom</label>
							<div class="controls">
								<input name="name" class="input-xlarge" id="article_field_name" type="text">
							</div>
						</div>
						<div class="control-group">
							<label class="control-label" for="article_field_stock">Stock</label>
							<div class="controls">
								<input name="stock" id="article_field_stock" class="input-xlarge" size="16" type="text">
							</div>
						</div>
						<div class="control-group">
							<label class="control-label" for="article_field_price">Prix</label>
							<div class="controls">
								<div class="input-prepend">
									<span class="add-on">€</span><input name="price" id="article_field_price" class="input-xlarge" size="16" type="text">
								</div>
							</div>
						</div>
						<div class="control-group">
							<label class="control-label" for="article_field_alcool">Alcool </label>
							<div class="controls">
									<input name="alcool" id="article_field_alcool" size="1" type="checkbox">
							</div>
						</div>
						<div class="form-actions">
							<button id="save_article" class="btn btn-success">
								<i class="icon-ok icon-white"></i>Sauvegarder
							</button>
							<button id="delete_article" class="btn btn-danger">
								<i class="icon-trash icon-white"></i>Supprimer
							</button>
						</div>
					</fieldset>
				</form>
			</div>
			
			<!--			CATEGORIE			-->
			<div id="categorie_details" style="display: none;">
				<h2><span id="categorie_name"></span> (#<span id="categorie_id"></span>)</h2>
				<form class="form-horizontal">
					<fieldset>
						<div class="control-group">
							<label class="control-label" for="categorie_field_name">Nom</label>
							<div class="controls">
								<input name="name" class="input-xlarge" id="categorie_field_name" type="text">
							</div>
						</div>
						<div class="control-group">
							<label class="control-label" for="categorie_field_parent_id">Parent</label>
							<div class="controls">
								<select name="parent_id" id="categorie_field_parent_id" class="input-xlarge">
									<?php foreach($this->param['categorie_parents'] as $parent)
										echo '<option value="'.$parent['id'].'">'.$parent['name'].'</option>';
									?>
								</select>
							</div>
						</div>
						<div class="control-group">
							<label class="control-label" for="categorie_field_fundation_id">Asso</label>
							<div class="controls">
								<select name="fundation_id" id="categorie_field_fundation_id" class="input-xlarge" disabled>
									<?php foreach($this->param['fundations'] as $fundation)
										echo '<option value="'.$fundation['id'].'">'.$fundation['name'].'</option>';
									?>
								</select>
							</div>
						</div>
						<div class="form-actions">
							<button id="save_categorie" class="btn btn-success">
								<i class="icon-ok icon-white"></i>Sauvegarder
							</button>
							<button id="delete_categorie" class="btn btn-danger">
								<i class="icon-trash icon-white"></i>Supprimer
							</button>
						</div>
					</fieldset>
				</form>
			</div>


			<!--					FUNDATION				-->
			<div id="fundation_details" style="display: none;">
				<h1><span id="fundation_name"></span> (#<span id="fundation_id"></span>)</h1>
				<div class="well" style="padding: 8px 0;">
					<table class="table table-striped">
						<thead>
							<tr>
								<td>#</td>
								<td>nom</td>
							</tr>
						</thead>
						<tbody id="fundation_categories">
						</tbody>
					</table>
				</div>
			</div>

			<!--					HOME					-->
			<div id="home" class="well">
				<h1>Yop !</h1>
				<p>
				Salut jeune padawan ! Ici tu vas pouvoir t'amuser à rajouter des articles
				à vendre à tous les soiffars de ce monde.
				</p>
				<p>
				Tchuss
				</p>
			</div>
			
		</div>
	</div><!--/span-->


</div><!--/row-->
