<?php

function helper_list_droits($droits, $remove_url, $services) {
    echo "<ul>";
    foreach($droits as $droit) {
        echo "<li>".$services->{$droit->service}->name." <a href=\"".$remove_url."&right=".$droit->service."\" ><i class=\"icon-remove\"></i></a></li>";
    }
    echo "</ul>";
}

?>

      <div class="row-fluid">
          <div class="hero-unit">
            <h1>Gestion des droits</h1>
          </div>
      </div><!--/row-->
            <div class="row-fluid">
                <h1>Droits des utilisateurs</h1>
                <?php if(isset($this->param['alert']["users"])) { 
                    $alert = $this->param['alert']["users"]; ?>
                  <div class="<?php echo $alert['class']; ?>">
                    <strong><?php echo $alert['strong']; ?></strong> <?php echo $alert['message']; ?>
                  </div>
                <?php } ?>
                <form class="well form-inline" method="POST" action="<?php echo $this->param['add_user_right']; ?>" >
                  <input type="text" class="input-small" name="login"placeholder="Login utc">
                  <select class="input-xlarge" name="right">
                    <option value=""></option>
                    <?php foreach($this->param['services'] as $service_name => $service) { ?>
                        <?php if($service->user) { ?>
                            <option value="<?php echo $service_name; ?>"><?php echo $service->name ?></option>
                        <?php } ?>
                    <?php } ?>
                  </select>
                  <select class="input-xlarge" name="fun_id">
                    <option value=""></option>
                    <?php foreach($this->param['fundations'] as $fun_id => $fun_name) { ?>
                        <option value="<?php echo $fun_id; ?>"><?php echo $fun_name ?></option>
                    <?php } ?>
                  </select>
                  <button type="submit" class="btn btn-success">Ajouter le droit</button>
                </form>
                <?php foreach($this->param['fundations'] as $fun_id => $fun_name) { 
                    $user_right = $this->param['user_right'][$fun_id];
                ?>
                    <h2><?php echo $fun_name; ?></h2>
                    <?php if(count($user_right) == 0) { ?>
                        <div class="alert alert-info">Aucun droit utilisateur n'a été donné sur cette fundation</div>
                    <?php } else { ?>
                        <table class="table table-striped table-bordered">
                            <thead>
                              <tr><th>Login</th><th>Nom</th><th>Prénom</th><th>Droits</th></tr>
                            </thead>
                            <tbody>
                            <?php foreach($user_right as $right) { ?>
                              <tr><td><?php echo $right->usr_login; ?></td>
                                  <td><?php echo $right->usr_lastname; ?></td>
                                  <td><?php echo $right->usr_firstname; ?></td>
                                  <td><?php helper_list_droits($right->service, 
                                                $this->param['remove_user_right']."&usr_id=".$right->usr_id."&fun_id=".$fun_id, 
                                                $this->param['services']); ?></td>
                              </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    <?php } ?>
                <?php } ?>
            </div>
            <div class="row-fluid">
                <h1>Droits des applications</h1>
                <?php if(isset($this->param['alert']["applications"])) { 
                    $alert = $this->param['alert']["applications"]; ?>
                  <div class="<?php echo $alert['class']; ?>">
                    <strong><?php echo $alert['strong']; ?></strong> <?php echo $alert['message']; ?>
                  </div>
                <?php } ?>
                <form class="well form-inline" method="POST" action="<?php echo $this->param['add_app_right']; ?>" >
                  <select class="input-xlarge" name="app_id">
                    <option value=""></option>
                    <?php foreach($this->param['applications'] as $app) { ?>
                        <option value="<?php echo $app->app_id; ?>"><?php echo $app->app_name." - ".$app->app_desc; ?></option>
                    <?php } ?>
                  </select>
                  <select class="input-xlarge" name="right">
                    <option value=""></option>
                    <?php foreach($this->param['services'] as $service_name => $service) { ?>
                        <?php if($service->user) { ?>
                            <option value="<?php echo $service_name; ?>"><?php echo $service->name ?></option>
                        <?php } ?>
                    <?php } ?>
                  </select>
                  <select class="input-xlarge" name="fun_id">
                    <option value=""></option>
                    <?php foreach($this->param['fundations'] as $fun_id => $fun_name) { ?>
                        <option value="<?php echo $fun_id; ?>"><?php echo $fun_name ?></option>
                    <?php } ?>
                  </select>
                  <button type="submit" class="btn btn-success">Ajouter le droit</button>
                </form>
                <?php foreach($this->param['fundations'] as $fun_id => $fun_name) { 
                        $app_right = $this->param['app_right'][$fun_id]; ?>
                    <h2><?php echo $fun_name; ?></h2>
                    <?php if(count($app_right) == 0) { ?>
                        <div class="alert alert-info">Aucun droit utilisateur n'a été donné sur cette fundation</div>
                    <?php } else { ?>
                        <table class="table table-striped table-bordered">
                            <thead>
                              <tr><th>Nom</th><th>Description</th><th>Droits</th></tr>
                            </thead>
                            <tbody>
                            <?php foreach($app_right as $right) { ?>
                              <tr><td><?php echo $this->param['applications'][$right->app_id]->app_name; ?></td>
                                  <td><?php echo $this->param['applications'][$right->app_id]->app_desc; ?></td>
                                  <td><?php helper_list_droits($right->service, 
                                                    $this->param['remove_app_right']."&app_id=".$right->app_id."&fun_id=".$fun_id, 
                                                    $this->param['services']); ?></td>
                              </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    <?php } ?>
                <?php } ?>
            </div>
            <br />
          </div>
